apiVersion: v1
kind: Service
metadata:
  name: kube-ops-view
  namespace: kube-ops-view
  labels:
    app: kube-ops-view
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: kube-ops-view
