apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - git-repo.yaml
  - kustomization-flux.yaml
  - frontend-lb.yaml
  - hpa.yaml
  - vpa.yaml
  - traefik-ingress.yaml
